print(('\033[1;34m========= Lojas MAGNATA =========\033[m'))
print('-' * 33)
valor = float(input('Valor das compras:(R$) '))
print('-' * 33)
print()
print('Escolha a baixo o tipo de pagamento:')
print('[ 1 ] à vista dinheiro/Cheque')
print('[ 2 ] à vista cartão de crédito')
print('[ 3 ] 2x no cartão')
print('[ 4 ] 3x ou mais no cartão')
print()
opção = int(input('Digite a opção de pagamento: '))
if opção == 1:
    print('=' * 74)
    print('Escolhendo a opção de comprar a vista você ganha 10% de desconto! :)')
    print('Sua compra de R${:.2f} fica R${:.2f}'.format(valor, (valor * 90) / 100))
    print('=' * 74)
    print('=' * 74)
    print('\033[33mObrigado por ter escolhido a Lojas Dourado, esperamos que volte sempre :)\033[m')
    print('=' * 74)
elif opção == 2:
    print('=' * 74)
    print('Escolhendo a opção de pagar a vista pelo cartão você ganha 5% de desconto! :)')
    print('Sua compra de R${:.2f} fica R${:.2f}'.format(valor, (valor * 95) / 100))
    print('=' * 74)
    print('=' * 74)
    print('\033[33mObrigado por ter escolhido a Lojas Dourado, esperamos que volte sempre :)\033[m')
    print('=' * 74)
elif opção == 3:
    print('=' * 74)
    print('Escolhendo a opção de pagar 2x pelo cartão não há adicional de juros!')
    print('Sua compra de R$ {:.2f} ficou no valor de 2x R${:.2f}'.format(valor, valor / 2))
    print('=' * 74)
    print('=' * 74)
    print('\033[33mObrigado por ter escolhido a Lojas Dourado, esperamos que volte sempre :)\033[m')
    print('=' * 74)
elif opção == 4:
    print('Escolhendo a opção de pagar 3x ou mais pelo cartão terá um adicional de juros!')
    prestacao = int(input('Em quantas vezes deseja pagar? '))
    juros = (valor * 0.20) / prestacao
    parcela = (valor / prestacao) + juros
    print('Sua compra de R${:.2f} parcelada em {}x de R${:.2f} com juros'.format(valor, prestacao, parcela))
    print('vai custar R${:.2f} no final'.format((valor * 0.20) + valor))
    print('=' * 74)
    print('\033[33mObrigado por ter escolhido a Lojas Dourado, esperamos que volte sempre :)\033[m')
    print('=' * 74)